# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
lune = "filiptibell/lune@0.7.7"
rbxcloud = "Sleitnick/rbxcloud@0.5.0"