name: pkg

on:
  push:
    branches:
    - main

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:

      - name: Download repository
        uses: actions/checkout@master

      - name: Extract Lync
        run: |
          ls
          mv Lync/ ../temp/
          rm -r *
          mv -v ../temp/* ./
          ls
      
      - name: Install Node.js
        uses: actions/setup-node@master

      - name: Install pkg
        run: npm install pkg

      - name: Compile Lync binary
        run: |
          cd Lync
          pkg index.js -t node18-win,node18-macos,node18-linux