name: Package Release

on:
  release:
    types: [published]

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:

    - name: Download repository
      uses: actions/checkout@master

    - name: Extract Lync
      run: |
        mv Lync/ ../temp/
        rm -r *
        mv -v ../temp/* ./
      
    - name: Install Node.js
      uses: actions/setup-node@master

    - name: Install pkg
      run: npm install -g pkg

    - name: Compile Lync binaries
      run: |
        pkg index.js -t node18-win,node18-macos,node18-linux
        ls

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@main
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Windows
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./index-win.exe
        asset_name: lync-windows-${{ steps.get_release.outputs.tag_name }}.exe
        asset_content_type: application/octet-stream

    - name: Upload MacOS
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./index-macos
        asset_name: lync-macos-${{ steps.get_release.outputs.tag_name }}
        asset_content_type: application/octet-stream

    - name: Upload Linux
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./index-linux
        asset_name: lync-linux-${{ steps.get_release.outputs.tag_name }}
        asset_content_type: application/octet-stream