name: Build and Publish Sample Project

on:
  push:
    branches:
    - main
    paths:
    - 'Lync/**'
    - 'Sample Project/**'

jobs:

  publish-main:
    runs-on: windows-latest
    steps:

    - name: Download repository
      uses: actions/checkout@master

    # Exclusive to the sample workflow; please this step!
    - name: Extract Sample Project
      run: |
        MOVE "Sample Project" "../temp"
        Get-ChildItem "./" -Recurse | Remove-Item -Recurse
        MOVE "../temp/*" "./"
        DIR

    # aftman.toml is currently required to download Lune and build offline.
    - name: Setup Aftman
      uses: ok-nick/setup-aftman@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Example - Keep if your project uses Wally packages.
    - name: Download Wally packages
      run: wally install

    - name: Install Node.js
      uses: actions/setup-node@master

    - name: Download Lync
      uses: actions/checkout@master
      with:
        repository: Iron-Stag-Games/Lync
        path: Lync

    - name: Build
      run: node "Lync/Lync/index.js" default.project.json OFFLINE

    # Remove this step to test build success without publishing.
    - name: Publish
      run: rbxcloud experience publish -f "BuildScripts/Build/Build.rbxl" -p ${{ secrets.PLACE_ID }} -u ${{ secrets.EXPERIENCE_ID }} -t published -a ${{ secrets.API_KEY }}