name: Upload Zip Files to Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          win-x64,
          macos-x64,
          macos-arm64,
          linux-x64,
          linux-arm64
        ]
    steps:

    - name: Download repository
      uses: actions/checkout@master

    - name: Zip Lync
      run: |
        cd Lync
        if [[ ${{ matrix.os }} == "win-x64" ]]; then
          mv lync-${{ matrix.os }}.exe lync.exe
          zip lync-${{ matrix.os }}.zip lync.exe lync-config.json
        else
          mv lync-${{ matrix.os }} lync
          zip lync-${{ matrix.os }}.zip lync lync-config.json
        fi

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@main
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload zip file
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: Lync/lync-${{ matrix.os }}.zip
        asset_name: lync-${{ steps.get_release.outputs.tag_name }}-${{ matrix.os }}.zip
        asset_content_type: application/zip
